version: "3.7"

services:
  database-rentx: #service name
    image: postgres
    container_name: database-rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app: #service name
    build: .
    container_name: rentx
    ports:
      - 3333:3333 #app
      - 9229:9229 #debugger
    volumes:
      - .:/usr/app
    links:
      - database-rentx
    depends_on:
      - database-rentx

volumes:
  pgdata:
    driver: local
